apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: where-for-dinner-search.my-apps.tap.20240118171321.0.0+build.02e9424
spec:
  refName: where-for-dinner-search.my-apps.tap
  version: 20240118171321.0.0+build.02e9424
  releaseNotes: |
    Release v20240118171321.0.0+build.02e9424 of package where-for-dinner-search.my-apps.tap
  template:
    spec:
      fetch:
      - imgpkgBundle:
          image: dev.registry.tanzu.vmware.com/tanzu-application-platform/ci-pipeline/apps-16-01-2024-17-05-54-249711819/where-for-dinner-search-my-apps-bundle@sha256:7d80a8408540985e3a6fbed3dd463fcc6980ef9aafc3ea763c8bbdf530a3f18e
      template:
      - ytt:
          paths:
          - .
      - kbld:
          paths:
          - .imgpkg/images.yml
          - '-'
      deploy:
      - kapp: {}
  valuesSchema:
    openAPIv3:
      type: object
      additionalProperties: false
      properties:
        workload_name:
          type: string
          default: ""

