apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: where-for-dinner-search.my-apps.tap.20240119051936.0.0+build.02e9424
spec:
  refName: where-for-dinner-search.my-apps.tap
  version: 20240119051936.0.0+build.02e9424
  releaseNotes: |
    Release v20240119051936.0.0+build.02e9424 of package where-for-dinner-search.my-apps.tap
  template:
    spec:
      fetch:
      - imgpkgBundle:
          image: dev.registry.tanzu.vmware.com/tanzu-application-platform/ci-pipeline/apps-16-01-2024-17-05-54-249711819/where-for-dinner-search-my-apps-bundle@sha256:f2033cf99b28e00a8dde9a2f5b9e85082da849636589ad93c607cfc10dbe6539
      template:
      - ytt:
          paths:
          - .
      - kbld:
          paths:
          - .imgpkg/images.yml
          - '-'
      deploy:
      - kapp: {}
  valuesSchema:
    openAPIv3:
      type: object
      additionalProperties: false
      properties:
        workload_name:
          type: string
          default: ""

