apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: where-for-dinner.my-apps.tap.20240117093536.0.0+build.02e9424
spec:
  refName: where-for-dinner.my-apps.tap
  version: 20240117093536.0.0+build.02e9424
  releaseNotes: |
    Release v20240117093536.0.0+build.02e9424 of package where-for-dinner.my-apps.tap
  template:
    spec:
      fetch:
      - imgpkgBundle:
          image: dev.registry.tanzu.vmware.com/tanzu-application-platform/ci-pipeline/apps-16-01-2024-17-05-54-249711819/where-for-dinner-my-apps-bundle@sha256:fd4b2518bf14f5180ed995368963ffb0cf3ad7acef7c0878acded9e1278804e0
      template:
      - ytt:
          paths:
          - .
      - kbld:
          paths:
          - .imgpkg/images.yml
          - '-'
      deploy:
      - kapp: {}
  valuesSchema:
    openAPIv3:
      type: object
      additionalProperties: false
      properties:
        workload_name:
          type: string
          default: ""

