apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: where-for-dinner.my-apps.tap.20240117230832.0.0+build.02e9424
spec:
  refName: where-for-dinner.my-apps.tap
  version: 20240117230832.0.0+build.02e9424
  releaseNotes: |
    Release v20240117230832.0.0+build.02e9424 of package where-for-dinner.my-apps.tap
  template:
    spec:
      fetch:
      - imgpkgBundle:
          image: dev.registry.tanzu.vmware.com/tanzu-application-platform/ci-pipeline/apps-16-01-2024-17-05-54-249711819/where-for-dinner-my-apps-bundle@sha256:670d5a045939191664e20e02ce4ed691518b9282f2e802cbbc8b74cf9c2b51f0
      template:
      - ytt:
          paths:
          - .
      - kbld:
          paths:
          - .imgpkg/images.yml
          - '-'
      deploy:
      - kapp: {}
  valuesSchema:
    openAPIv3:
      type: object
      additionalProperties: false
      properties:
        workload_name:
          type: string
          default: ""

