apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: where-for-dinner.my-apps.tap.20240121110321.0.0+build.02e9424
spec:
  refName: where-for-dinner.my-apps.tap
  version: 20240121110321.0.0+build.02e9424
  releaseNotes: |
    Release v20240121110321.0.0+build.02e9424 of package where-for-dinner.my-apps.tap
  template:
    spec:
      fetch:
      - imgpkgBundle:
          image: dev.registry.tanzu.vmware.com/tanzu-application-platform/ci-pipeline/apps-16-01-2024-17-05-54-249711819/where-for-dinner-my-apps-bundle@sha256:ff04ddf64c561c6a3cc6c90cdb4948d4dc616708a4a47e0fe7a82532b7981be0
      template:
      - ytt:
          paths:
          - .
      - kbld:
          paths:
          - .imgpkg/images.yml
          - '-'
      deploy:
      - kapp: {}
  valuesSchema:
    openAPIv3:
      type: object
      additionalProperties: false
      properties:
        workload_name:
          type: string
          default: ""

