apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: where-for-dinner-availability.my-apps.tap.20240121175146.0.0+build.02e9424
spec:
  refName: where-for-dinner-availability.my-apps.tap
  version: 20240121175146.0.0+build.02e9424
  releaseNotes: |
    Release v20240121175146.0.0+build.02e9424 of package where-for-dinner-availability.my-apps.tap
  template:
    spec:
      fetch:
      - imgpkgBundle:
          image: dev.registry.tanzu.vmware.com/tanzu-application-platform/ci-pipeline/apps-16-01-2024-17-05-54-249711819/where-for-dinner-availability-my-apps-bundle@sha256:c771a19e00c4880da6786abedb4323fa6b898b36228162397ed330c1a1d12ac1
      template:
      - ytt:
          paths:
          - .
      - kbld:
          paths:
          - .imgpkg/images.yml
          - '-'
      deploy:
      - kapp: {}
  valuesSchema:
    openAPIv3:
      type: object
      additionalProperties: false
      properties:
        workload_name:
          type: string
          default: ""

