apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: where-for-dinner-availability.my-apps.tap.20240118093655.0.0+build.02e9424
spec:
  refName: where-for-dinner-availability.my-apps.tap
  version: 20240118093655.0.0+build.02e9424
  releaseNotes: |
    Release v20240118093655.0.0+build.02e9424 of package where-for-dinner-availability.my-apps.tap
  template:
    spec:
      fetch:
      - imgpkgBundle:
          image: dev.registry.tanzu.vmware.com/tanzu-application-platform/ci-pipeline/apps-16-01-2024-17-05-54-249711819/where-for-dinner-availability-my-apps-bundle@sha256:d209b4871c0cd84b6d84597e2498b394c9c0ee469f4169666f7ec5c902560e30
      template:
      - ytt:
          paths:
          - .
      - kbld:
          paths:
          - .imgpkg/images.yml
          - '-'
      deploy:
      - kapp: {}
  valuesSchema:
    openAPIv3:
      type: object
      additionalProperties: false
      properties:
        workload_name:
          type: string
          default: ""

