apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: where-for-dinner-notify.my-apps.tap.20240118093709.0.0+build.02e9424
spec:
  refName: where-for-dinner-notify.my-apps.tap
  version: 20240118093709.0.0+build.02e9424
  releaseNotes: |
    Release v20240118093709.0.0+build.02e9424 of package where-for-dinner-notify.my-apps.tap
  template:
    spec:
      fetch:
      - imgpkgBundle:
          image: dev.registry.tanzu.vmware.com/tanzu-application-platform/ci-pipeline/apps-16-01-2024-17-05-54-249711819/where-for-dinner-notify-my-apps-bundle@sha256:f890cf3462e025ef94e11b1371fc4be78102771cc1dea62cfdbfa097c12ba835
      template:
      - ytt:
          paths:
          - .
      - kbld:
          paths:
          - .imgpkg/images.yml
          - '-'
      deploy:
      - kapp: {}
  valuesSchema:
    openAPIv3:
      type: object
      additionalProperties: false
      properties:
        workload_name:
          type: string
          default: ""

